before_script:
  - pip install -r requirements.txt

stages:
  - greeting
  - test

greet:
  stage: greeting
  image: python:3.8
  script:
    - echo "Hello! My name is $MY_LOGIN. My password is $MY_PASSWORD."

lintest:
  stage: test
  image: python:3.8
  script:
    - pip install flake8
    - flake8 .
  allow_failure: true
  only:
    - merge_requests

unit_test:
  stage: test
  image: python:3.8
  script:
    - pytest tests/unit
  only:
    - merge_requests

integration_test:
  stage: int_test
  image: python:3.8
  script:
    - pytest tests/integration
  when: manual
  only:
    - merge_requests
  needs: [ "unit_test" ]